logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

jjwt:
  access-token:
    expired-time: 720
    secret-key: access_secret
  refresh-token:
    expired-time: 1440
    secret-key: refresh_secret

security:
  un-security:
    list:
      - GET /specification/index.html
      - GET /healthcheck

spring:
  r2dbc:
    url: r2dbc:mariadb://125.240.27.115:17001/alarm-project
    username: root
    password: 1234

server:
  image-url: http://mysend.co.kr:8080/image
  image-path: /image?fileName=